-- Add new cat breeds (ignore duplicates)
INSERT INTO cat_breeds (name, name_tr, origin) VALUES
('British Longhair', 'British Longhair', 'İngiltere'),
('Scottish Straight', 'Scottish Straight', 'İskoçya'),
('Himalayan', 'Himalaya Kedisi', 'ABD'),
('Burmese', 'Burma Kedisi', 'Myanmar'),
('Tonkinese', 'Tonkinese', 'Kanada'),
('Somali', 'Somali', 'ABD'),
('Oriental Shorthair', 'Oriental Shorthair', 'Tayland'),
('Devon Rex', 'Devon Rex', 'İngiltere'),
('Cornish Rex', 'Cornish Rex', 'İngiltere'),
('Chartreux', 'Chartreux (Kartezyen)', 'Fransa'),
('Balinese', 'Bali Kedisi', 'ABD'),
('Savannah', 'Savannah', 'ABD'),
('Munchkin', 'Munchkin', 'ABD'),
('Manx', 'Manx', 'Man Adası'),
('American Shorthair', 'Amerikan Shorthair', 'ABD'),
('American Curl', 'Amerikan Curl', 'ABD'),
('Ragamuffin', 'Ragamuffin', 'ABD'),
('Singapura', 'Singapura', 'Singapur'),
('Selkirk Rex', 'Selkirk Rex', 'ABD'),
('Egyptian Mau', 'Mısır Mau', 'Mısır'),
('Ocicat', 'Ocicat', 'ABD'),
('Snowshoe', 'Snowshoe', 'ABD'),
('Bombay', 'Bombay', 'ABD'),
('Burmilla', 'Burmilla', 'İngiltere'),
('Havana Brown', 'Havana Brown', 'İngiltere'),
('Korat', 'Korat', 'Tayland'),
('LaPerm', 'LaPerm', 'ABD'),
('Nebelung', 'Nebelung', 'ABD'),
('Toyger', 'Toyger', 'ABD'),
('Chinchilla', 'Chinchilla', 'İngiltere')
ON CONFLICT (name) DO NOTHING;

-- Add new dog breeds (ignore duplicates)
INSERT INTO dog_breeds (name, name_tr, origin, size_category) VALUES
('Toy Poodle', 'Toy Kaniş', 'Fransa', 'mini'),
('Miniature Poodle', 'Minyatür Kaniş', 'Fransa', 'small'),
('Alaskan Malamute', 'Alaskan Malamute', 'ABD', 'large'),
('Springer Spaniel', 'Springer Spaniel', 'İngiltere', 'medium'),
('Cavalier King Charles', 'Cavalier King Charles', 'İngiltere', 'small'),
('Doberman', 'Doberman', 'Almanya', 'large'),
('Boxer', 'Boxer', 'Almanya', 'large'),
('Great Dane', 'Danua (Great Dane)', 'Almanya', 'giant'),
('Bernese Mountain Dog', 'Bern Dağ Köpeği', 'İsviçre', 'giant'),
('Saint Bernard', 'Saint Bernard', 'İsviçre', 'giant'),
('Border Collie', 'Border Collie', 'İngiltere', 'medium'),
('Australian Shepherd', 'Avustralya Çoban Köpeği', 'ABD', 'medium'),
('Corgi', 'Corgi (Pembroke)', 'Galler', 'small'),
('Jack Russell Terrier', 'Jack Russell Terrier', 'İngiltere', 'small'),
('Bull Terrier', 'Bull Terrier', 'İngiltere', 'medium'),
('Staffordshire Bull Terrier', 'Staffordshire Bull Terrier', 'İngiltere', 'medium'),
('American Bully', 'Amerikan Bully', 'ABD', 'medium'),
('Pit Bull Terrier', 'Pit Bull Terrier', 'ABD', 'medium'),
('Cane Corso', 'Cane Corso', 'İtalya', 'large'),
('Akita Inu', 'Akita Inu', 'Japonya', 'large'),
('Shiba Inu', 'Shiba Inu', 'Japonya', 'small'),
('Shar Pei', 'Shar Pei', 'Çin', 'medium'),
('Chow Chow', 'Chow Chow', 'Çin', 'medium'),
('Samoyed', 'Samoyed', 'Rusya', 'medium'),
('Weimaraner', 'Weimaraner', 'Almanya', 'large'),
('Dalmatian', 'Dalmaçyalı', 'Hırvatistan', 'large'),
('Miniature Schnauzer', 'Minyatür Schnauzer', 'Almanya', 'small'),
('Giant Schnauzer', 'Dev Schnauzer', 'Almanya', 'large'),
('West Highland Terrier', 'West Highland Terrier', 'İskoçya', 'small'),
('Bichon Frise', 'Bichon Frise', 'Fransa', 'small'),
('Havanese', 'Havanese', 'Küba', 'small'),
('Papillon', 'Papillon', 'Fransa', 'mini'),
('Lhasa Apso', 'Lhasa Apso', 'Tibet', 'small'),
('Pekingese', 'Pekinez', 'Çin', 'small'),
('Basenji', 'Basenji', 'Kongo', 'medium'),
('Whippet', 'Whippet', 'İngiltere', 'medium'),
('Greyhound', 'Greyhound', 'İngiltere', 'large'),
('Irish Setter', 'İrlanda Setter', 'İrlanda', 'large'),
('Vizsla', 'Vizsla', 'Macaristan', 'medium'),
('Belgian Malinois', 'Belçika Malinois', 'Belçika', 'large'),
('Newfoundland', 'Newfoundland', 'Kanada', 'giant'),
('Leonberger', 'Leonberger', 'Almanya', 'giant'),
('Malaklı', 'Malaklı', 'Türkiye', 'giant'),
('Boz Çoban', 'Boz Çoban Köpeği', 'Türkiye', 'giant'),
('Tazi', 'Tazı', 'Türkiye', 'medium')
ON CONFLICT (name) DO NOTHING;
